# ------------------------------------------------------------
# Base: Miniconda (conda + Python)
# ------------------------------------------------------------
FROM continuumio/miniconda3:latest

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# ------------------------------------------------------------
# Install system dependencies
# ------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    git \
    tini \
    texlive-latex-base \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-fonts-recommended \
	texlive-fonts-extra \
    texlive-xetex \
    latexmk \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# ------------------------------------------------------------
# Install Quarto CLI
# ------------------------------------------------------------
RUN wget https://quarto.org/download/latest/quarto-linux-amd64.deb \
    && dpkg -i quarto-linux-amd64.deb \
    && rm quarto-linux-amd64.deb


# ------------------------------------------------------------
# Copy environment.yml into container
# ------------------------------------------------------------
COPY mlmiin26.yml /tmp/mlmiin26.yml

# ------------------------------------------------------------
# Create conda environment
# ------------------------------------------------------------
RUN conda env create -f /tmp/mlmiin26.yml && conda clean -afy

# Set environment
ENV CONDA_DEFAULT_ENV=mlmiin
ENV PATH=/opt/conda/envs/mlmiin/bin:$PATH

# Configure Jupyter to have no token/password and listen on all interfaces
RUN mkdir -p /root/.jupyter && \
    echo "c.ServerApp.token = ''" >> /root/.jupyter/jupyter_server_config.py && \
    echo "c.ServerApp.password = ''" >> /root/.jupyter/jupyter_server_config.py && \
    echo 'c.ServerApp.ip = "0.0.0.0"' >> /root/.jupyter/jupyter_server_config.py && \
    echo "c.ServerApp.allow_root = True" >> /root/.jupyter/jupyter_server_config.py

# ------------------------------------------------------------
# Set the working directory
# ------------------------------------------------------------
RUN mkdir -p /wd

# Set it as the default working directory
WORKDIR /wd

# ------------------------------------------------------------
# JupyterLab config (optional)
# ------------------------------------------------------------
EXPOSE 8888

# This ensures ctrl+C works cleanly
ENTRYPOINT ["tini", "--"]

# Default command: start JupyterLab
CMD ["bash", "-c", "jupyter lab --ip=0.0.0.0 --no-browser --allow-root"]
